# Generated by Django 2.2.7 on 2019-12-04 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=datetime.time),
        ),
    ]
