# Generated by Django 2.2.7 on 2019-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191204_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Other', max_length=30),
        ),
    ]
