# Generated by Django 3.0 on 2019-12-18 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_event_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='going',
            field=models.ManyToManyField(blank=True, related_name='going', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
