# Generated by Django 3.0 on 2019-12-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191222_1627'),
        ('events', '0013_auto_20191222_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventsCreated', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='going',
            field=models.ManyToManyField(blank=True, related_name='going', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interested', to='users.UserProfile'),
        ),
    ]
