# Generated by Django 3.0 on 2019-12-17 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
