# Generated by Django 3.0 on 2019-12-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='_userprofile_following_+', to='users.UserProfile'),
        ),
    ]
