# Generated by Django 3.0 on 2019-12-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_following_+', to='users.UserProfile'),
        ),
    ]
